version: '3.9'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: titan_chest
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql

  titan-chest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: titan-chest-api
    volumes:
      - .:/app
    ports:
      - 2000:2000
    restart: always

volumes:
  mysql:

networks:
  default:
    external:
      name: titan-chest-network
